-- Phase 8 portable state checkpoint.
-- Runtime SQLite is generated by scripts/record_phase8_ledger.py after the acceptance exam.
BEGIN;
CREATE TABLE IF NOT EXISTS phase8_security_controls (control_id TEXT PRIMARY KEY,status TEXT NOT NULL,evidence TEXT NOT NULL,updated_at TEXT NOT NULL);
INSERT INTO phase8_security_controls VALUES
('authentication','DONE','waf/security/production_security.py + tests/test_phase8_security.py','phase8'),
('rbac','DONE','explicit viewer/operator/reviewer/admin permissions','phase8'),
('secrets','DONE','fail-closed production configuration validation','phase8'),
('privacy_audit','DONE','identifier-only audit record contract','phase8'),
('supabase_rls','DONE','20260917120000_phase8_security.sql','phase8'),
('live_supabase','OPEN','requires real Supabase environment and migration execution','phase8'),
('api_auth_wiring','OPEN','requires production FastAPI adapter integration','phase8');
CREATE TABLE IF NOT EXISTS phase8_tasks (task TEXT PRIMARY KEY,status TEXT NOT NULL,evidence TEXT NOT NULL);
INSERT INTO phase8_tasks VALUES
('production auth/RBAC','DONE','security package + dedicated tests'),
('secret/config hygiene','DONE','fail-closed production validation'),
('privacy/data minimization','DONE','identifier-only audit contract'),
('Supabase security migration','DONE','RLS + role helpers + anon revocation'),
('live Supabase application','OPEN','external deployment verification'),
('FastAPI endpoint auth wiring','OPEN','adapter integration remains'),
('ModSecurity/Coraza + TLS','OPEN','external deployment verification'),
('load/failure + challenge evidence','OPEN','later milestones'),
('dashboard/demo/report','OPEN','later milestones'),
('final release gate','OPEN','blocked until all milestones verified');
COMMIT;
