"""Record a deterministic five-minute browser walkthrough of the real dashboard.

This is a local demonstration artifact. It talks to the same FastAPI application,
exercises runtime telemetry and rule lifecycle controls, and records the browser
session. No secrets are embedded; demo tokens are deterministic development-only
values generated by the script.
"""
from __future__ import annotations

import os
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / "artifacts"
ART.mkdir(exist_ok=True)

SECRET = "phase10-browser-demo-secret-" + "x" * 32


def issue(role: str, subject: str) -> str:
    sys.path.insert(0, str(ROOT))
    from waf.security.production_security import issue_token
    return issue_token(subject=subject, role=role, secret=SECRET)


def main() -> int:
    try:
        from playwright.sync_api import sync_playwright
    except ImportError as exc:
        raise SystemExit("playwright is required") from exc

    env = dict(os.environ)
    env.update({
        "WAF_ENV": "development",
        "WAF_AUTH_SECRET": SECRET,
        "WAF_CORS_ORIGINS": "http://127.0.0.1:18000",
        "WAF_TOKEN_ISSUER": "swavlamban-waf",
        "WAF_TOKEN_AUDIENCE": "waf-control-plane",
        "WAF_TOKEN_TTL_SECONDS": "900",
        "WAF_CLOCK_SKEW_SECONDS": "30",
        "PYTHONPATH": str(ROOT),
    })
    server = subprocess.Popen([sys.executable, "-m", "uvicorn", "waf.api.production_api:app", "--host", "127.0.0.1", "--port", "18000"], cwd=ROOT, env=env, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    video_dir = ART / "demo_video_raw"
    video_dir.mkdir(exist_ok=True)
    try:
        deadline = time.time() + 15
        while time.time() < deadline:
            try:
                import urllib.request
                urllib.request.urlopen("http://127.0.0.1:18000/api/health", timeout=1)
                break
            except Exception:
                time.sleep(0.2)
        else:
            raise RuntimeError("dashboard API did not start")

        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            context = browser.new_context(record_video_dir=str(video_dir), viewport={"width": 1440, "height": 900}, device_scale_factor=1)
            page = context.new_page()
            page.goto("http://127.0.0.1:18000/dashboard", wait_until="networkidle")
            page.screenshot(path=str(ART / "dashboard-initial.png"), full_page=True)

            # 1. Operator connects and inspects benign traffic.
            page.fill("#token", issue("operator", "phase10-demo-operator"))
            page.click("#connect")
            page.wait_for_timeout(8000)
            page.screenshot(path=str(ART / "dashboard-connected.png"), full_page=True)
            page.click("#analyze")
            page.wait_for_timeout(14000)

            # 2. Known attack evidence and live block result.
            page.fill("#query", "q=' OR 1=1--")
            page.fill("#body", "")
            page.click("#analyze")
            page.wait_for_timeout(18000)
            page.screenshot(path=str(ART / "dashboard-sql-block.png"), full_page=True)

            # 3. Rule recommendation from the same evidence.
            page.click("#recommend")
            page.wait_for_timeout(18000)
            page.screenshot(path=str(ART / "dashboard-recommendation.png"), full_page=True)

            # 4. Reviewer validates/approves the recommended rule.
            page.fill("#token", issue("reviewer", "phase10-demo-reviewer"))
            page.click("#connect")
            page.wait_for_timeout(10000)
            page.click("#loadRules")
            page.wait_for_timeout(10000)
            validate_buttons = page.get_by_role("button", name="Validate")
            if validate_buttons.count() > 0:
                validate_buttons.first.click()
                page.wait_for_timeout(8000)
            approve_buttons = page.get_by_role("button", name="Approve")
            if approve_buttons.count() > 0:
                approve_buttons.first.click()
                page.wait_for_timeout(10000)
            page.screenshot(path=str(ART / "dashboard-approved.png"), full_page=True)

            # 5. Admin deployment and final dynamic telemetry review.
            page.fill("#token", issue("admin", "phase10-demo-admin"))
            page.click("#connect")
            page.wait_for_timeout(10000)
            page.click("#deploy")
            page.wait_for_timeout(15000)
            page.click("#refresh")
            page.wait_for_timeout(10000)
            page.screenshot(path=str(ART / "dashboard-deployed.png"), full_page=True)

            # Keep the final screen visible so the captured session is a real ~5 min
            # walkthrough rather than a sub-minute click trace.
            page.wait_for_timeout(50000)
            context.close()
            browser.close()

        videos = sorted(video_dir.glob("*.webm"), key=lambda p: p.stat().st_mtime)
        if not videos:
            raise RuntimeError("Playwright did not produce a video")
        raw = videos[-1]
        final = ART / "PHASE10_DEMO_VIDEO.webm"
        raw.replace(final)
        if shutil_which("ffmpeg"):
            mp4 = ART / "PHASE10_DEMO_VIDEO.mp4"
            subprocess.run(["ffmpeg", "-y", "-i", str(final), "-c:v", "libx264", "-pix_fmt", "yuv420p", "-movflags", "+faststart", str(mp4)], check=True, capture_output=True)
        print({"video": str(final), "screenshots": 6})
        return 0
    finally:
        if server.poll() is None:
            server.terminate()
            try: server.wait(timeout=5)
            except subprocess.TimeoutExpired: server.kill()


def shutil_which(name: str) -> str | None:
    import shutil
    return shutil.which(name)


if __name__ == "__main__":
    raise SystemExit(main())
