#!/usr/bin/env python3
"""Record the complete Phase 9 checkpoint into the portable SQLite+SQL ledger."""
from __future__ import annotations
import hashlib,json,platform,shutil,sqlite3,subprocess
from datetime import datetime,timezone
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; DB=ROOT/'state/project_ledger.db'; SQL=ROOT/'state/phase9_ledger.sql'; NOW=datetime.now(timezone.utc).isoformat()
def sha256(path): return hashlib.sha256(path.read_bytes()).hexdigest()
def pytest_count(check):
    value=check.get('passed_tests'); return int(value) if isinstance(value,int) else 0
def capture(cmd):
    try:
        p=subprocess.run(cmd,capture_output=True,text=True,timeout=10); return p.stdout.strip() or p.stderr.strip()
    except Exception as exc: return f'unavailable: {exc}'
def main():
    result=json.loads((ROOT/'phase9_master_exam_result.json').read_text(encoding='utf-8'))
    if result['status']!='PASS' or result['score']<9.9 or result['critical_defects']: raise SystemExit('Phase 9 master result is not a clean PASS')
    checks={item['name']:item for item in result['checks']}; regression=pytest_count(checks['full-regression']); continuity=pytest_count(checks['phase8-security-continuity']); api=pytest_count(checks['phase9-api-tests'])
    con=sqlite3.connect(DB); cur=con.cursor(); cur.execute('''CREATE TABLE IF NOT EXISTS phase9_integration_evidence (evidence_id TEXT PRIMARY KEY,category TEXT NOT NULL,status TEXT NOT NULL,summary TEXT NOT NULL,artifact_path TEXT NOT NULL,measured_at TEXT NOT NULL)''')
    cur.execute('DELETE FROM test_runs WHERE phase=9'); cur.execute('DELETE FROM change_log WHERE phase=9'); cur.execute('DELETE FROM artifacts WHERE phase=9'); cur.execute("DELETE FROM environment_snapshot WHERE key LIKE 'phase9.%'"); cur.execute('DELETE FROM phase9_integration_evidence'); cur.execute('DELETE FROM tasks WHERE phase=9')
    cur.execute('INSERT OR REPLACE INTO phases VALUES (?,?,?,?,?,?,?)',(9,'Production runtime integration and Challenge 3 evidence','PASS',float(result['score']),float(result['cutoff']),f'Clean executable Phase 9 gate: {regression}/{regression} full regression, {continuity}/{continuity} Phase 8 continuity, {api}/{api} API tests, compile/static/TLS/scenario gates PASS; zero failed critical checks.',NOW))
    metadata={'phase9.status':'COMPLETE_VERIFIED_LOCAL','phase9.scope':'production-facing API integration + server persistence + privacy lockdown + local TLS + Challenge 3 evidence','validation.phase9_master_exam':f"{result['score']:.1f}/10.0; cutoff {result['cutoff']}; critical defects 0",'validation.phase9_full_regression':f'{regression}/{regression} PASS','validation.phase9_phase8_continuity':f'{continuity}/{continuity} PASS','validation.phase9_api_tests':f'{api}/{api} PASS','validation.phase9_compileall':'PASS','validation.phase9_static_contract':'PASS','validation.phase9_tls':'nginx config PASS; HTTPS allow 200; HTTPS SQL block 403','validation.phase9_scenarios':'baseline allow; HTTPS inspected; known SQL/XSS and command variant blocked; API behavioural escalation observed','validation.phase9_performance':json.dumps(checks['challenge-scenario-gate'].get('performance',{}),sort_keys=True),'validation.phase9_ci':'NOT_OBSERVED until a Phase 9 PR-triggered GitHub Actions run is observed','validation.phase9_first_failures':'API fixture used expired fixed-time tokens; corrected to current-time token issue. TLS smoke used /health against basic upstream; corrected to /. Initial local archive lacked branch-existing Phase 8 hardening surfaces; reconciled from phase9-final branch.','external.infrastructure':'live Supabase credentials unavailable; external certificates unavailable; ModSecurity/Coraza module absent; Internet-scale load environment unavailable'}
    for k,v in metadata.items(): cur.execute('INSERT OR REPLACE INTO project_meta(key,value,updated_at) VALUES (?,?,?)',(k,v,NOW))
    tasks=[('secure FastAPI runtime boundary','DONE','waf/api/production_api.py + backend/server.py'),('Phase 8 auth/RBAC continuity','DONE','tests/test_phase8_security.py + tests/test_phase8_security_hardening.py'),('server-only Supabase persistence','DONE','waf/storage/production.py'),('legacy Supabase runtime lockdown','DONE','supabase/migrations/20260917150000_phase9_runtime_security.sql'),('privacy-safe runtime telemetry','DONE','raw body/headers/query excluded; source identity hashed'),('local HTTPS/TLS edge integration','DONE','scripts/phase9_tls_smoke.py + phase9_tls_evidence.json'),('Challenge 3 deterministic scenario evidence','DONE','phase9_scenario_evidence.json'),('in-process performance evidence','DONE','500 decisions with mean/p95/p99 and derived throughput'),('live Supabase migration','OPEN','requires real Supabase URL and server-only service role key'),('external HTTPS certificate operations','OPEN','requires target deployment DNS/certificate environment'),('ModSecurity/Coraza runtime integration','OPEN','module absent in verification environment'),('Internet-scale distributed load/failure validation','OPEN','requires dedicated deployment/load environment'),('authenticated dashboard UX','OPEN','frontend authentication/session wiring and visual validation'),('five-minute deterministic demo','OPEN','submission recording milestone'),('final technical report/slides','OPEN','2-3 page document + 8-10 slide presentation'),('final release candidate gate','OPEN','after deployment evidence and submission assets')]
    for task,status,evidence in tasks: cur.execute('INSERT INTO tasks(phase,task,status,evidence,updated_at) VALUES (?,?,?,?,?)',(9,task,status,evidence,NOW))
    changes=[('IMPLEMENT','waf/api/production_api.py','Secure FastAPI runtime boundary with bearer auth, RBAC, request validation, security headers and WebSocket auth.'),('IMPLEMENT','waf/storage/production.py','Server-only REST adapter; runtime telemetry is sanitized and source identity is hashed.'),('IMPLEMENT','supabase/migrations/20260917150000_phase9_runtime_security.sql','Revoked permissive legacy access, added role-gated reads, service-role writes, raw-material cleanup and future privacy checks.'),('RECONCILE','waf/core/config.py','Preserved pre-existing phase9-final production config fields while adding testable env mapping support.'),('RECONCILE','Phase 8 hardening surfaces','Restored branch-existing auth/rbac/secrets/storage modules and hardening migration/test into the portable checkpoint.'),('VERIFY','tests/test_phase9_production_api.py',f'Dedicated Phase 9 API/RBAC/privacy suite completed {api}/{api} PASS.'),('REMEDIATE','tests/test_phase9_production_api.py','Initial API fixture failures came from expired fixed-time tokens; fixture corrected to current-time token issuance.'),('REMEDIATE','scripts/phase9_tls_smoke.py','Initial local smoke used /health against a basic upstream; switched to /; final allow 200 and SQL block 403.'),('VERIFY','scripts/phase9_scenario_benchmark.py','Challenge 3 deterministic scenarios and 500-request in-process performance measurement completed.'),('VERIFY','scripts/phase9_master_exam.py',f"{result['score']:.1f}/10.0 PASS; {regression}/{regression} regression; {continuity}/{continuity} continuity; {api}/{api} API; zero failed critical checks."),('HONESTY','external infrastructure boundary','No live Supabase, public certificate operation, ModSecurity/Coraza installation or Internet-scale load claim is made.')]
    for a,t,d in changes: cur.execute('INSERT INTO change_log(phase,action,target,details,created_at) VALUES (?,?,?,?,?)',(9,a,t,d,NOW))
    for name,check in checks.items(): cur.execute('INSERT INTO test_runs(phase,name,status,score,details,run_at) VALUES (?,?,?,?,?,?)',(9,name,'PASS' if check.get('passed') else 'FAIL',10.0 if check.get('passed') else 0.0,json.dumps(check,sort_keys=True),NOW))
    for path,ver in [('phase9_master_exam_result.json','phase9'),('phase9_scenario_evidence.json','phase9'),('phase9_tls_evidence.json','phase9'),('scripts/phase9_master_exam.py','phase9'),('scripts/phase9_scenario_benchmark.py','phase9'),('scripts/phase9_tls_smoke.py','phase9'),('waf/api/production_api.py','phase9'),('waf/storage/production.py','phase9'),('state/phase9_ledger.sql','phase9')]:
        f=ROOT/path
        if f.exists(): cur.execute('INSERT INTO artifacts(phase,path,version,sha256,bytes,metadata,recorded_at) VALUES (?,?,?,?,?,?,?)',(9,path,ver,sha256(f),f.stat().st_size,json.dumps({'master_status':result['status']}),NOW))
    evidence=[('API-RUNTIME','api','PASS',f'FastAPI auth/RBAC runtime boundary exercised by TestClient ({api}/{api} tests).','waf/api/production_api.py'),('SUPABASE-ADAPTER','storage','PASS','Server-only REST adapter sanitizes telemetry and hashes source identifiers.','waf/storage/production.py'),('SUPABASE-RLS','database','PASS','Legacy runtime tables locked down; raw fields scrubbed and future checks added.','supabase/migrations/20260917150000_phase9_runtime_security.sql'),('HTTPS-LOCAL','tls','PASS','nginx syntax PASS; HTTPS allow 200; SQL block 403 through live WAF edge.','phase9_tls_evidence.json'),('CHALLENGE-SCENARIOS','challenge','PASS','Baseline, HTTPS, known attacks, command variant and API behavioural evidence PASS.','phase9_scenario_evidence.json'),('PERFORMANCE','performance','PASS','500 in-process decisions measured with mean/p95/p99 and derived throughput.','phase9_scenario_evidence.json'),('CONTINUITY','regression','PASS',f'Phase 1-8 behaviour retained across {regression}/{regression} full tests and {continuity}/{continuity} Phase 8 security continuity tests.','phase9_master_exam_result.json')]
    for row in evidence: cur.execute('INSERT OR REPLACE INTO phase9_integration_evidence VALUES (?,?,?,?,?,?)',(*row,NOW))
    env={'phase9.python':capture(['python','--version']),'phase9.platform':platform.platform(),'phase9.nginx':'present' if shutil.which('nginx') else 'absent','phase9.openssl':'present' if shutil.which('openssl') else 'absent','phase9.curl':'present' if shutil.which('curl') else 'absent','phase9.live_supabase_credentials':'not provided','phase9.external_certificate':'not provided','phase9.modsecurity_coraza':'module absent from verification environment'}
    for k,v in env.items(): cur.execute('INSERT OR REPLACE INTO environment_snapshot(key,value,captured_at) VALUES (?,?,?)',(k,v,NOW))
    con.commit(); SQL.write_text('\n'.join(con.iterdump())+'\n',encoding='utf-8'); con.close(); print(json.dumps({'db':str(DB),'db_sha256':sha256(DB),'sql':str(SQL),'sql_sha256':sha256(SQL),'full_regression':regression,'continuity':continuity,'api_tests':api},indent=2))
if __name__=='__main__': raise SystemExit(main())
